Repository gobelinmalin/bordeaux_0320_p3_admin_giftcard, pull requests merged in 2020-07, with the labels that each got.

#8 Feat/crud client
  .gitignore
  src/components/customers/AddCustomer.jsx
  src/components/customers/AllCustomers.jsx
  src/components/customers/Customers.jsx
  src/components/customers/DeleteCustomer.jsx
  src/components/customers/TableCustomer.jsx
  src/components/customers/UpdateCustomer.jsx
Labels: pr ON develop

#9 Feat/cockpit
  package-lock.json
  package.json
  src/App.jsx
  src/components/Cockpit.jsx
  src/components/DisplayContent.jsx
  src/components/boardchart/BoardChart.jsx
  src/components/customers/AllCustomers.jsx
  src/components/customers/Customers.jsx
  src/components/customers/FormCustomer.jsx
  src/components/navbar/NavBar.jsx
  src/components/navbar/NavButton.jsx
  src/components/navbar/style/left-menu-style.css
  src/components/shops/Shops.jsx
  src/components/styles.css
Labels: pr ON develop

#10 Feat/cockpit
  src/App.jsx
  src/components/Cockpit.jsx
  src/components/DisplayContent.jsx
  src/components/shops/Shops.jsx
Labels: pr ON develop

#13 Feat/crud client
  src/App.jsx
  src/components/customers/AddCustomer.jsx
  src/components/customers/AllCustomers.jsx
  src/components/customers/Customers.jsx
  src/components/customers/CustomersList.jsx
  src/components/customers/DeleteCustomer.jsx
  src/components/customers/FormCustomer.jsx
  src/components/customers/UpdateCustomer.jsx
  src/components/customers/customerFields.js
  src/components/shops/ShopDetail.jsx
  src/components/shops/Shops.jsx
  src/components/shops/ShopsAdd.jsx
  src/components/shops/ShopsUpdate.jsx
Labels: pr ON develop

#15 Feat/crud client
  src/components/customers/AddCustomer.jsx
  src/components/customers/Customers.jsx
  src/components/customers/CustomersList.jsx
  src/components/customers/UpdateCustomer.jsx
Labels: pr ON develop

#20 sort filter done and working on OrdersList.jsx
  src/components/orders/OrdersList.jsx
Labels: pr ON develop

#21 Feat/team
  src/App.jsx
  src/components/admins/AdminAdd.jsx
  src/components/admins/Admins.jsx
  src/components/customers/AddCustomer.jsx
  src/components/customers/Customers.jsx
  src/components/customers/CustomersList.jsx
  src/components/navbar/datas.js
  src/components/orders/Orders.jsx
  src/components/orders/OrdersList.jsx
  src/components/orders/orders.css
Labels: pr ON develop

#22 npm update
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/components/admins/AdminUpdate.jsx
  src/components/customers/CustomersList.jsx
  src/components/customers/customers.css
  src/components/orders/OrdersList.jsx
  src/components/orders/orders.css
  src/index.css
Labels: pr ON develop

#23 Add all orders for one customer : OdersByCustomers.jsx
  src/App.jsx
  src/components/orders/Orders.jsx
  src/components/orders/OrdersByCustomer.jsx
  src/components/orders/OrdersList.jsx
Labels: pr ON develop

#24 Update CSS
  src/App.jsx
  src/components/admins/AdminAdd.jsx
  src/components/admins/Admins.jsx
  src/components/shops/Shops.jsx
  src/components/shops/shops.css
  src/index.css
Labels: pr ON develop

#25 Feat/products crud
  package-lock.json
  package.json
  src/App.jsx
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
  src/components/products/ProductsNavbar.jsx
  src/components/products/products.css
  src/components/shops/Shops.jsx
Labels: pr ON develop

#32 Fix/clean branch
  package-lock.json
  package.json
  src/components/Cockpit.jsx
  src/components/DisplayContent.jsx
  src/components/admins/AdminUpdate.jsx
  src/components/deliveries/Deliveries.jsx
  src/components/editBar/EditBar.jsx
  src/components/editBar/EditButton.jsx
  src/components/editBar/edit-bar.css
  src/components/editBar/edit-button.css
  src/components/navbar/Logo.jsx
  src/components/navbar/NavBar.css
  src/components/orders/Orders.jsx
  src/components/orders/OrdersList.jsx
  src/components/shops/ShopsAdd.jsx
Labels: bug, pr ON develop

#34 Feat/team
  package-lock.json
  package.json
  server.js
  src/components/admins/AdminAdd.jsx
  src/components/admins/AdminUpdate.jsx
  src/components/admins/Admins.jsx
  src/components/admins/admins.css
  src/components/customers/AddCustomer.jsx
  src/components/customers/Customers.jsx
  src/components/customers/CustomersList.jsx
  src/components/customers/UpdateCustomer.jsx
  src/components/orders/AddOrder.jsx
  src/components/orders/Orders.jsx
  src/components/orders/OrdersByCustomer.jsx
  src/components/orders/UpdateOrder.jsx
  src/components/shops/ShopDetail.jsx
  src/components/shops/Shops.jsx
  src/components/shops/ShopsAdd.jsx
  src/components/shops/ShopsUpdate.jsx
  src/index.css
Labels: pr ON develop

#26 Develop
  .gitignore
  package-lock.json
  package.json
  public/index.html
  server.js
  src/App.css
  src/App.jsx
  src/components/Signin.jsx
  src/components/admins/AdminAdd.jsx
  src/components/admins/AdminUpdate.jsx
  src/components/admins/Admins.jsx
  src/components/admins/admins.css
  src/components/boardchart/BoardChart.jsx
  src/components/content-section.css
  src/components/customers/AddCustomer.jsx
  src/components/customers/Customers.jsx
  src/components/customers/CustomersList.jsx
  src/components/customers/UpdateCustomer.jsx
  src/components/customers/customerFields.js
  src/components/customers/customers.css
  src/components/header/Header.jsx
  src/components/header/header.css
  src/components/navbar/Logo.jsx
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.jsx
  src/components/navbar/NavButton.jsx
  src/components/navbar/datas.js
  src/components/orders/AddOrder.jsx
  src/components/orders/Orders.jsx
  src/components/orders/OrdersByCustomer.jsx
  src/components/orders/OrdersList.jsx
  src/components/orders/UpdateOrder.jsx
  src/components/orders/orders.css
  src/components/orders/ordersFields.js
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
  src/components/products/ProductsNavbar.jsx
  src/components/products/products.css
  src/components/shops/ShopDetail.jsx
  src/components/shops/Shops.jsx
  src/components/shops/ShopsAdd.jsx
  src/components/shops/ShopsUpdate.jsx
  src/components/shops/shops.css
  src/components/signin.css
  src/components/styles.css
  src/img/logo-givyoo.jpg
  src/index.css
  src/index.jsx
Labels: WEEKLY

#35 Deploy/update
  package-lock.json
  package.json
  server.js
  src/components/products/Products.jsx
Labels: pr ON develop

#38 Feat/login
  package-lock.json
  package.json
  src/App.jsx
  src/components/PrivateRoutes.jsx
  src/components/Profile.jsx
  src/components/Signin.jsx
  src/components/dashboard/Dashboard.jsx
  src/components/header/Header.jsx
  src/components/navbar/NavBar.css
  src/components/navbar/datas.js
  src/components/products/CardAdd.jsx
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
  src/components/shops/ShopSearch.jsx
  src/components/shops/ShopsAdd.jsx
  src/components/signin.css
  src/contexts/AuthContext.jsx
  src/index.jsx
Labels: pr ON develop

#39 fix Routing with "exact path"
  src/App.jsx
Labels: pr ON develop

#40 Feat/products crud
  src/App.jsx
  src/components/products/CardAdd.jsx
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
  src/components/products/ProductsNavbar.jsx
  src/components/shops/ShopsAdd.jsx
  src/components/shops/ShopsUpdate.jsx
Labels: pr ON develop

#42 Feat/categories
  src/App.jsx
  src/components/categories/Categories.jsx
  src/components/categories/CategoryAdd.jsx
  src/components/categories/CategoryUpdate.jsx
  src/components/products/ProductsNavbar.jsx
Labels: pr ON develop

#43 Feat/uploadimg
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
  src/components/shops/ShopsAdd.jsx
Labels: pr ON develop

#49 fix bugs
  src/components/categories/Categories.jsx
  src/components/shops/ShopsAdd.jsx
Labels: pr ON develop

#52 Feat/product update
  src/components/products/CardAdd.jsx
  src/components/products/CardsProducts.jsx
  src/components/products/Products.jsx
  src/components/products/ProductsAdd.jsx
Labels: pr ON develop
